### ISSUE TITLE
it does not work

### ISSUE THREAD

**Issue by lenoedit** [Mattewn99/Instagram-Autogagement#13]
MINGW64 ~/autoga
$ py post.py
Traceback (most recent call last):
  File "C:\Users\Leno1\autoga\post.py", line 1, in <module>
    from utils.log import Log
  File "C:\Users\Leno1\autoga\utils\log.py", line 1, in <module>
    from termcolor import colored
ModuleNotFoundError: No module named 'termcolor'

**Comment by Mattewn99** [comment]
Hello, have you installed the dependencies?

**Comment by IAMDROPPE** [comment]
> Hola, has instalado las dependencias?

Muchas de las dependencias no se pueden instalar.
Detalles:
Python 3.10.4
pip 22.1.1


Uno de los errores:
Collecting modulegraph==0.10.4
  Downloading modulegraph-0.10.4.tar.gz (532 kB)
     ---------------------------------------- 532.2/532.2 kB 954.2 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting moviepy==0.2.3.2
  Downloading moviepy-0.2.3.2-py2.py3-none-any.whl (122 kB)
     ---------------------------------------- 123.0/123.0 kB 1.2 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement mysql-connector-python-cext==8.0.16 (from versions: none)
ERROR: No matching distribution found for mysql-connector-python-cext==8.0.16
